sudo: required
services:
    - docker

before_install:
    - docker build -t asethi06/basic-react-app -f Dockerfile.dev .



script:
    - docker run -e CI=true asethi06/basic-react-app npm run test -- --coverage

deploy:
    # deploy app as front end website
    - provider: heroku
        skip_cleanup: true
        api-key:
            secure: $HEROKU_API_KEY
        app: basic-react-app-pipeline
       