sudo: required
services:
    - docker

before_install:
    - docker build -t asethi06/basic-react-app -f Dockerfile.dev .



script:
    - docker run -e CI=true asethi06/basic-react-app npm run test -- --coverage
    - docker run -e CI=true asethi06/basic-react-app npm run build -- --coverage

deploy:
    provider: heroku
    skip_cleanup: true
    api-key: $HEROKU_API_KEY
    app: basic-react-app-pipeline
    on:
        branch: master
       